/*
격자판 : n x n, 흰색, 빨간색, 파란색 중 하나의 색
말 : k개, 모두 격자판의 한 지점, 1번부터 k번까지 번호 지정, 이동 방향(상하좌우)

턴 한 번동안 1번말부터 k번 말까지 순서대로 움직임
- 말이 이동하려는 칸이 흰색인 경우에는 해당 칸으로 이동
이동하려는 칸에 말이 이미 있는 경우에는 해당 말 위에 이동하려던 말을 올려둠
이미 말이 올려져 있는 상태에도 말을 올릴 수 있음
- 이동하려는 칸이 빨간색인 경우에는 해당 칸으로 이동하기 전 순서를 뒤집음
이후 해당 칸에 말이 있는 경우에는 흰색 칸과 같이 그 위에 쌓음
- 이동하려는 칸이 파란색일 경우에는 이동하지 않고 방향을 반대로 전환한 뒤 이동
만일 반대 방향으로 전환한 뒤 이동하려는 칸도 파란색이라면 방향만 반대로 전환한 뒤 이동하지 않고 가만히 있음
이동하려는 말에 다른 말들이 쌓여있을 경우에 이동하려는 말만 방향을 반대로 바꿔야 함에 유의
- 격자판의 범위를 벗어나는 이동일 경우 파란색으로 이동하려는 것과 똑같이 생각하여 처리
- 쌓여있는 말을 이동하는 경우에는 본인 위에 있는 말과 함께 이동

게임이 진행되는 동안 아직 한 턴이 다 끝나지 않은 경우더라도 말이 4개 이상 겹쳐지는 경우가 생긴다면 그 즉시 게임을 종료

게임이 종료되는 턴의 번호를 출력, 답이 1000보다 크거나 불가능한 경우에는 -1을 출력
*/
#define _CRT_SECURE_NO_WARNINGS
#include <iostream>
#include <vector>
#include <tuple>
using namespace std;

const int MAXN = 12;
const int MAXK = 10;

int n, k;
int grid[MAXN + 10][MAXN + 10];
vector<int> horse[MAXN + 10][MAXN + 10];
int horse_d[MAXK + 10];

int dx[4] = { 0,1,0,-1 };
int dy[4] = { 1,0,-1,0 };

void print() {
	cout << "grid" << "\n";
    	for (int i = 0; i < n; i++) {
        		for (int j = 0; j < n; j++) {
                			cout << grid[i][j] << " ";
                            		}
                                    		cout << "\n";
                                            	}
                                                	cout << "\n";

                                                    	cout << "horse" << "\n";
                                                        	for (int x = 0; x < n; x++) {
                                                            		for (int y = 0; y < n; y++) {
                                                                    			cout << "{ ";
                                                                                			for (int i = 0; i < (int)horse[x][y].size(); i++) {
                                                                                            				cout << horse[x][y][i] << " ";
                                                                                                            			}
                                                                                                                        			cout << "} ";
                                                                                                                                    		}
                                                                                                                                            		cout << "\n";
                                                                                                                                                    	}
                                                                                                                                                        	cout << "\n";

                                                                                                                                                            	cout << "horse_d" << "\n";
                                                                                                                                                                	for (int i = 1; i <= k; i++) {
                                                                                                                                                                    		cout << i << " : " << horse_d[i] << "\n";
                                                                                                                                                                            	}
                                                                                                                                                                                	cout << "\n";
                                                                                                                                                                                    }

                                                                                                                                                                                    bool isOver() {
                                                                                                                                                                                    	for (int x = 0; x < n; x++) {
                                                                                                                                                                                        		for (int y = 0; y < n; y++) {
                                                                                                                                                                                                			if ((int)horse[x][y].size() >= 4) return true;
                                                                                                                                                                                                            		}
                                                                                                                                                                                                                    	}
                                                                                                                                                                                                                        	return false;
                                                                                                                                                                                                                            }

                                                                                                                                                                                                                            /*
                                                                                                                                                                                                                            턴 한 번동안 1번말부터 k번 말까지 순서대로 움직임
                                                                                                                                                                                                                            - 말이 이동하려는 칸이 흰색인 경우에는 해당 칸으로 이동
                                                                                                                                                                                                                            이동하려는 칸에 말이 이미 있는 경우에는 해당 말 위에 이동하려던 말을 올려둠
                                                                                                                                                                                                                            이미 말이 올려져 있는 상태에도 말을 올릴 수 있음
                                                                                                                                                                                                                            - 이동하려는 칸이 빨간색인 경우에는 해당 칸으로 이동하기 전 순서를 뒤집음
                                                                                                                                                                                                                            이후 해당 칸에 말이 있는 경우에는 흰색 칸과 같이 그 위에 쌓음
                                                                                                                                                                                                                            - 이동하려는 칸이 파란색일 경우에는 이동하지 않고 방향을 반대로 전환한 뒤 이동
                                                                                                                                                                                                                            만일 반대 방향으로 전환한 뒤 이동하려는 칸도 파란색이라면 방향만 반대로 전환한 뒤 이동하지 않고 가만히 있음
                                                                                                                                                                                                                            이동하려는 말에 다른 말들이 쌓여있을 경우에 이동하려는 말만 방향을 반대로 바꿔야 함에 유의
                                                                                                                                                                                                                            - 격자판의 범위를 벗어나는 이동일 경우 파란색으로 이동하려는 것과 똑같이 생각하여 처리
                                                                                                                                                                                                                            - 쌓여있는 말을 이동하는 경우에는 본인 위에 있는 말과 함께 이동
                                                                                                                                                                                                                            */

                                                                                                                                                                                                                            bool inRange(int x, int y) {
                                                                                                                                                                                                                            	return (x >= 0 && x < n && y >= 0 && y < n);
                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                tuple<int, int, int> findPos(int id) {
                                                                                                                                                                                                                                	for (int x = 0; x < n; x++) {
                                                                                                                                                                                                                                    		for (int y = 0; y < n; y++) {
                                                                                                                                                                                                                                            			for (int i = 0; i < (int)horse[x][y].size(); i++) {
                                                                                                                                                                                                                                                        				if (horse[x][y][i] == id)  return { x, y, i };
                                                                                                                                                                                                                                                                        			}
                                                                                                                                                                                                                                                                                    		}
                                                                                                                                                                                                                                                                                            	}
                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                void movePlayer(int id) {
                                                                                                                                                                                                                                                                                                	int cx, cy, cd, order;
                                                                                                                                                                                                                                                                                                    	tie(cx, cy, order) = findPos(id);
                                                                                                                                                                                                                                                                                                        	cd = horse_d[id];

                                                                                                                                                                                                                                                                                                            	int nx = cx + dx[cd];
                                                                                                                                                                                                                                                                                                                	int ny = cy + dy[cd];
                                                                                                                                                                                                                                                                                                                    	int sz = 0; // pop할때는 벡터의 사이즈가 줄어듬!!! 따라서 임시 변수에 크기를 저장해두고 for문을 사용해야함!

                                                                                                                                                                                                                                                                                                                        	if (!inRange(nx, ny) || grid[nx][ny] == 2) {
                                                                                                                                                                                                                                                                                                                            		cd = (cd + 2) % 4;
                                                                                                                                                                                                                                                                                                                                    		horse_d[id] = cd;

                                                                                                                                                                                                                                                                                                                                            		nx = cx + dx[cd];
                                                                                                                                                                                                                                                                                                                                                    		ny = cy + dy[cd];

                                                                                                                                                                                                                                                                                                                                                            		if (inRange(nx, ny) && grid[nx][ny] == 0) {
                                                                                                                                                                                                                                                                                                                                                                    			for (int i = order; i < (int)horse[cx][cy].size(); i++) {
                                                                                                                                                                                                                                                                                                                                                                                				horse[nx][ny].push_back(horse[cx][cy][i]);
                                                                                                                                                                                                                                                                                                                                                                                                			}
                                                                                                                                                                                                                                                                                                                                                                                                            			
                                                                                                                                                                                                                                                                                                                                                                                                                        			sz = (int)horse[cx][cy].size();
                                                                                                                                                                                                                                                                                                                                                                                                                                    			for (int i = order; i < sz; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                				horse[cx][cy].pop_back();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                			}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		else if (inRange(nx, ny) && grid[nx][ny] == 1) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            			for (int i = (int)horse[cx][cy].size() -1; i >= order; i--) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        				horse[nx][ny].push_back(horse[cx][cy][i]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        			}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    			sz = (int)horse[cx][cy].size();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                			for (int i = sz - 1; i >= order; i--) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            				horse[cx][cy].pop_back();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            			}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	else if(grid[nx][ny] == 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		for (int i = order; i < (int)horse[cx][cy].size(); i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                			horse[nx][ny].push_back(horse[cx][cy][i]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		sz = (int)horse[cx][cy].size();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		for (int i = order; i < sz; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    			horse[cx][cy].pop_back();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	else if (grid[nx][ny] == 1) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		for (int i = (int)horse[cx][cy].size() - 1; i >= order; i--) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        			horse[nx][ny].push_back(horse[cx][cy][i]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		int sz = (int)horse[cx][cy].size();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		for (int i = sz - 1; i >= order; i--) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            			horse[cx][cy].pop_back();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    int main() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	ios::sync_with_stdio(0); cin.tie(0); cout.tie(0);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	//freopen("sample_input.txt", "r", stdin);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	cin >> n >> k;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	for (int i = 0; i < n; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		for (int j = 0; j < n; j++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            			cin >> grid[i][j];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	for (int i = 1; i <= k; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		int x, y, d; cin >> x >> y >> d;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		x--;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		y--;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		if (d == 1) d = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		else if (d == 2) d = 2;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		else if (d == 3) d = 3;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		else if (d == 4) d = 1;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		horse[x][y].push_back(i);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		horse_d[i] = d;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	//print();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	for (int turn = 1; turn <= 1000; turn++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		//cout << "turn : " << turn << "\n";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		for (int i = 1; i <= k; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            			//cout << "movePlayer " << i << "\n";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        			movePlayer(i);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    			//print();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                			if (isOver()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            				cout << turn << "\n";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            				return 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            			}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	cout << -1 << "\n";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	return 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }