#define _CRT_SECURE_NO_WARNINGS
#include <iostream>
#include <algorithm>
using namespace std;

const int FOUR = 4;
const int TEN = 10;

const int START = 0;
const int END = 20;

int move_num[TEN + 10]; // 이동 칸 수
int horse[FOUR + 10]; // 말의 위치 
int ans;

int point[] = { 0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,0,
				13,16,19,0,0,
                				22,24,0,0,0,
                                				28,27,26,0,0,
                                                				25,30,35,40 };

                                                                bool isOverlapped() {
                                                                	for (int i = 0; i < FOUR - 1; i++) {
                                                                    		for (int j = i + 1; j < FOUR; j++) {
                                                                            			if (horse[i] == horse[j] && horse[i] != START && horse[i] != END) return true;
                                                                                        		}
                                                                                                	}
                                                                                                    	return false;
                                                                                                        }

                                                                                                        int getNextPos(int dist, int cur_pos) {
                                                                                                        	if (cur_pos == 5) {
                                                                                                            		cur_pos = 21;
                                                                                                                    		dist--;
                                                                                                                            	}
                                                                                                                                	else if (cur_pos == 10) {
                                                                                                                                    		cur_pos = 26;
                                                                                                                                            		dist--;
                                                                                                                                                    	}
                                                                                                                                                        	else if (cur_pos == 15) {
                                                                                                                                                            		cur_pos = 31;
                                                                                                                                                                    		dist--;
                                                                                                                                                                            	}

                                                                                                                                                                                	while (dist--) {
                                                                                                                                                                                    		if (cur_pos == 23 || cur_pos == 27 || cur_pos == 33) {
                                                                                                                                                                                            			cur_pos = 36;
                                                                                                                                                                                                        			continue;
                                                                                                                                                                                                                    		}
                                                                                                                                                                                                                            		if (cur_pos == 19) {
                                                                                                                                                                                                                                    			cur_pos = 39;
                                                                                                                                                                                                                                                			continue;
                                                                                                                                                                                                                                                            		}
                                                                                                                                                                                                                                                                    		if (cur_pos == 39) {
                                                                                                                                                                                                                                                                            			cur_pos = END;
                                                                                                                                                                                                                                                                                        			return END;
                                                                                                                                                                                                                                                                                                    		}

                                                                                                                                                                                                                                                                                                            		cur_pos++;
                                                                                                                                                                                                                                                                                                                    		if (cur_pos == END) return END;
                                                                                                                                                                                                                                                                                                                            	}

                                                                                                                                                                                                                                                                                                                                	return cur_pos;
                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                    void selectHorse(int cnt, int score) {
                                                                                                                                                                                                                                                                                                                                    	if (cnt == TEN) {
                                                                                                                                                                                                                                                                                                                                        		ans = max(ans, score);
                                                                                                                                                                                                                                                                                                                                                		return;
                                                                                                                                                                                                                                                                                                                                                        	}

                                                                                                                                                                                                                                                                                                                                                            	for (int i = 0; i < FOUR; i++) {
                                                                                                                                                                                                                                                                                                                                                                		if (horse[i] == END) continue;

                                                                                                                                                                                                                                                                                                                                                                        		int tmp = horse[i];
                                                                                                                                                                                                                                                                                                                                                                                		horse[i] = getNextPos(move_num[cnt], horse[i]);
                                                                                                                                                                                                                                                                                                                                                                                        		if (!isOverlapped()) selectHorse(cnt + 1, score + point[horse[i]]);
                                                                                                                                                                                                                                                                                                                                                                                                		horse[i] = tmp;
                                                                                                                                                                                                                                                                                                                                                                                                        	}
                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                            int main() {
                                                                                                                                                                                                                                                                                                                                                                                                            	ios::sync_with_stdio(0); cin.tie(0); cout.tie(0);
                                                                                                                                                                                                                                                                                                                                                                                                                	//freopen("sample_input.txt", "r", stdin);

                                                                                                                                                                                                                                                                                                                                                                                                                    	for (int i = 0; i < TEN; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                        		cin >> move_num[i];
                                                                                                                                                                                                                                                                                                                                                                                                                                	}
                                                                                                                                                                                                                                                                                                                                                                                                                                    	for (int i = 0; i < FOUR; i++) horse[i] = START;

                                                                                                                                                                                                                                                                                                                                                                                                                                        	ans = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                            	selectHorse(0, 0);

                                                                                                                                                                                                                                                                                                                                                                                                                                                	cout << ans << "\n";
                                                                                                                                                                                                                                                                                                                                                                                                                                                    	return 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                        /*
                                                                                                                                                                                                                                                                                                                                                                                                                                                        다 뽑아두고 뽑아둔 결과로 다음 코드를 작성했는데
                                                                                                                                                                                                                                                                                                                                                                                                                                                        이 문제는 뽑는 중간에 불가능한 경우를 배제

                                                                                                                                                                                                                                                                                                                                                                                                                                                        backtracking에서는 탐색 크기가 너무 커지지 않도록 불가능한 경우를 최대한 빨리 제거하는 것이 핵심
                                                                                                                                                                                                                                                                                                                                                                                                                                                        */