/*
격자 : n x n
플레이어 : 번호, 위치, 향하는 방향, 초기 능력치, 점수. 총

각각의 격자에는 무기들이 있을 수 있음
초기에는 무기들이 없는 빈 격자에 플레이어들이 위치
각 플레이어는 초기 능력치를 가짐
각 플레이어의 초기 능력치는 모두 다름

1-1. 첫번째 플레이어부터 순차적으로 본인이 향하고 있는 방향대로 한 칸만큼 이동
만약 해당 방향으로 나갈 때 격자를 벗어나는 경우에는 정반대 방향으로 방향을 바꾸어서 1만큼 이동

2-1. 만약 이동한 방향에 플레이어가 없다면 해당 칸에 총이 있는지 확인
총이 있는 경우, 해당 플레이어는 총을 획득
플레이어가 이미 총을 가지고 있는 경우에는 놓여있는 총들과 플레이어가 가지고 있는 총 가운데 공격력이 더 쎈 총을 획득하고,
나머지 총들은 해당 격자에 둠

2-2-1. 만약 이동한 방향에 플레이어가 있는 경우에는 두 플레이어가 싸움
해당 플레이어의 초기 능력치와 가지고 있는 총의 공격력의 합을 비교하여 더 큰 플레이어가 이김
만일 이 수치가 같은 경우 플레이어의 초기 능력치가 높은 플레이어가 승리
이긴 플레이어는 각 플레이어의 초기 능력치와 가지고 있는 총의 공격력의 합의 차이만큼 포인트 획득

2-2-2. 진 플레이어는 본인이 가지고 있는 총을 해당 격자에 놓고, 해당 플레이어가 원래 가지고 있던 방향대로 한 칸 이동
만약 이동하려는 칸에 플레이어가 있거나 격자 범위 밖인 경우 오른쪽으로 90도씩 회전하여 빈 칸이 보이는 순간 이동
만약 해당 칸에 총이 있다면, 해당 플레이어는 가장 공격력이 높은 총을 획득하고 나머지 총들은 해당 격자에 내려둠

2-2-3. 이긴 플레이어는 승리한 칸에 떨어져 있는 총들과 원래 들고 있던 총 중 가장 공격력이 높은 총을 획득하고, 나머지 총들은 해당 격자에 내려둠
*/
#define _CRT_SECURE_NO_WARNINGS
#include <iostream>
#include <vector>
#include <algorithm>
using namespace std;

const int MAXN = 20;
const int MAXM = 30;

int n, m, k;
vector<int> gun_grid[MAXN + 10][MAXN + 10];

int player_x[MAXM + 10];
int player_y[MAXM + 10];
int player_d[MAXM + 10];
int player_s[MAXM + 10];
int player_g[MAXM + 10];
int score[MAXM + 10];

int dx[4] = { -1,0,1,0 };
int dy[4] = { 0,1,0,-1 };

void print() {
	cout << "gun_grid" << "\n";
    	for (int x = 0; x < n; x++) {
        		for (int y = 0; y < n; y++) {
                			cout << "{ ";
                            			for (int i = 0; i < (int)gun_grid[x][y].size(); i++) cout << gun_grid[x][y][i] << " ";
                                        			cout << "} ";
                                                    		}
                                                            		cout << "\n";
                                                                    	}
                                                                        	cout << "\n";

                                                                            	cout << "player" << "\n";
                                                                                	for (int i = 1; i <= m; i++) {
                                                                                    		cout << player_x[i] << " " << player_y[i] << " " << player_d[i] << " " << player_s[i] << " " << player_g[i] << " " << score[i] << "\n";
                                                                                            	}
                                                                                                	cout << "\n";
                                                                                                    }

                                                                                                    bool inRange(int x, int y) {
                                                                                                    	return (x >= 0 && x < n && y >= 0 && y < n);
                                                                                                        }

                                                                                                        int getIdx(int idx, int x, int y) {
                                                                                                        	for (int i = 1; i <= m; i++) {
                                                                                                            		if (i == idx) continue;
                                                                                                                    		if (player_x[i] == x && player_y[i] == y) return i;
                                                                                                                            	}
                                                                                                                                	return 0;
                                                                                                                                    }

                                                                                                                                    /*
                                                                                                                                    1-1. 첫번째 플레이어부터 순차적으로 본인이 향하고 있는 방향대로 한 칸만큼 이동
                                                                                                                                    만약 해당 방향으로 나갈 때 격자를 벗어나는 경우에는 정반대 방향으로 방향을 바꾸어서 1만큼 이동

                                                                                                                                    2-1. 만약 이동한 방향에 플레이어가 없다면 해당 칸에 총이 있는지 확인
                                                                                                                                    총이 있는 경우, 해당 플레이어는 총을 획득
                                                                                                                                    플레이어가 이미 총을 가지고 있는 경우에는 놓여있는 총들과 플레이어가 가지고 있는 총 가운데 공격력이 더 쎈 총을 획득하고,
                                                                                                                                    나머지 총들은 해당 격자에 둠

                                                                                                                                    2-2-1. 만약 이동한 방향에 플레이어가 있는 경우에는 두 플레이어가 싸움
                                                                                                                                    해당 플레이어의 초기 능력치와 가지고 있는 총의 공격력의 합을 비교하여 더 큰 플레이어가 이김
                                                                                                                                    만일 이 수치가 같은 경우 플레이어의 초기 능력치가 높은 플레이어가 승리
                                                                                                                                    이긴 플레이어는 각 플레이어의 초기 능력치와 가지고 있는 총의 공격력의 합의 차이만큼 포인트 획득

                                                                                                                                    2-2-2. 진 플레이어는 본인이 가지고 있는 총을 해당 격자에 놓고, 해당 플레이어가 원래 가지고 있던 방향대로 한 칸 이동
                                                                                                                                    만약 이동하려는 칸에 플레이어가 있거나 격자 범위 밖인 경우 오른쪽으로 90도씩 회전하여 빈 칸이 보이는 순간 이동
                                                                                                                                    만약 해당 칸에 총이 있다면, 해당 플레이어는 가장 공격력이 높은 총을 획득하고 나머지 총들은 해당 격자에 내려둠

                                                                                                                                    2-2-3. 이긴 플레이어는 승리한 칸에 떨어져 있는 총들과 원래 들고 있던 총 중 가장 공격력이 높은 총을 획득하고, 나머지 총들은 해당 격자에 내려둠
                                                                                                                                    */

                                                                                                                                    void loserMove(int idx) {
                                                                                                                                    	int cx = player_x[idx];
                                                                                                                                        	int cy = player_y[idx];
                                                                                                                                            	int cd = player_d[idx];

                                                                                                                                                	gun_grid[cx][cy].push_back(player_g[idx]);
                                                                                                                                                    	player_g[idx] = 0;

                                                                                                                                                        	int nx, ny;
                                                                                                                                                            	for (int cnt = 0; cnt < 4; cnt++) {
                                                                                                                                                                		nx = cx + dx[(cd + cnt) % 4];
                                                                                                                                                                        		ny = cy + dy[(cd + cnt) % 4];

                                                                                                                                                                                		if (getIdx(idx, nx, ny) != 0 || !inRange(nx, ny)) continue;
                                                                                                                                                                                        		player_x[idx] = nx;
                                                                                                                                                                                                		player_y[idx] = ny;
                                                                                                                                                                                                        		player_d[idx] = (cd + cnt) % 4;
                                                                                                                                                                                                                		break;
                                                                                                                                                                                                                        	}

                                                                                                                                                                                                                            	if (gun_grid[nx][ny].empty()) return;
                                                                                                                                                                                                                                	sort(gun_grid[nx][ny].begin(), gun_grid[nx][ny].end());
                                                                                                                                                                                                                                    	player_g[idx] = gun_grid[nx][ny].back();
                                                                                                                                                                                                                                        	gun_grid[nx][ny].pop_back();
                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                            void winnerMove(int idx) {
                                                                                                                                                                                                                                            	int cx = player_x[idx];
                                                                                                                                                                                                                                                	int cy = player_y[idx];

                                                                                                                                                                                                                                                    	if (player_g[idx] > 0) {
                                                                                                                                                                                                                                                        		gun_grid[cx][cy].push_back(player_g[idx]);
                                                                                                                                                                                                                                                                		player_g[idx] = 0;
                                                                                                                                                                                                                                                                        	}

                                                                                                                                                                                                                                                                            	if (gun_grid[cx][cy].empty()) return;
                                                                                                                                                                                                                                                                                	sort(gun_grid[cx][cy].begin(), gun_grid[cx][cy].end());
                                                                                                                                                                                                                                                                                    	player_g[idx] = gun_grid[cx][cy].back();
                                                                                                                                                                                                                                                                                        	gun_grid[cx][cy].pop_back();
                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                            void collide(int idx1, int idx2) {
                                                                                                                                                                                                                                                                                            	int winner, loser;
                                                                                                                                                                                                                                                                                                	if (player_s[idx1] + player_g[idx1] > player_s[idx2] + player_g[idx2]) {
                                                                                                                                                                                                                                                                                                    		winner = idx1;
                                                                                                                                                                                                                                                                                                            		loser = idx2;
                                                                                                                                                                                                                                                                                                                    	}
                                                                                                                                                                                                                                                                                                                        	else if (player_s[idx1] + player_g[idx1] < player_s[idx2] + player_g[idx2]) {
                                                                                                                                                                                                                                                                                                                            		winner = idx2;
                                                                                                                                                                                                                                                                                                                                    		loser = idx1;
                                                                                                                                                                                                                                                                                                                                            	}
                                                                                                                                                                                                                                                                                                                                                	else {
                                                                                                                                                                                                                                                                                                                                                    		if (player_s[idx1] > player_s[idx2]) {
                                                                                                                                                                                                                                                                                                                                                            			winner = idx1;
                                                                                                                                                                                                                                                                                                                                                                        			loser = idx2;
                                                                                                                                                                                                                                                                                                                                                                                    		}
                                                                                                                                                                                                                                                                                                                                                                                            		else{
                                                                                                                                                                                                                                                                                                                                                                                                    			winner = idx2;
                                                                                                                                                                                                                                                                                                                                                                                                                			loser = idx1;
                                                                                                                                                                                                                                                                                                                                                                                                                            		}
                                                                                                                                                                                                                                                                                                                                                                                                                                    	}

                                                                                                                                                                                                                                                                                                                                                                                                                                        	score[winner] += ((player_s[winner] + player_g[winner]) - (player_s[loser] + player_g[loser]));

                                                                                                                                                                                                                                                                                                                                                                                                                                            	loserMove(loser);
                                                                                                                                                                                                                                                                                                                                                                                                                                                	winnerMove(winner);
                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                    void moveAllPlayer() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    	for (int i = 1; i <= m; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        		int nx = player_x[i] + dx[player_d[i]];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                		int ny = player_y[i] + dy[player_d[i]];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		if (!inRange(nx, ny)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                			player_d[i] = (player_d[i] + 2) % 4;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            			nx = player_x[i] + dx[player_d[i]];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        			ny = player_y[i] + dy[player_d[i]];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		player_x[i] = nx;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		player_y[i] = ny;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		int oppo_idx = getIdx(i, nx, ny);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		if (oppo_idx == 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            			if (player_g[i] > 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        				gun_grid[nx][ny].push_back(player_g[i]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        				player_g[i] = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        			}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    			if (gun_grid[nx][ny].empty()) continue;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                			sort(gun_grid[nx][ny].begin(), gun_grid[nx][ny].end());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            			player_g[i] = gun_grid[nx][ny].back();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        			gun_grid[nx][ny].pop_back();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		else collide(i, oppo_idx);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        int main() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	ios::sync_with_stdio(0); cin.tie(0); cout.tie(0);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	//freopen("sample_input.txt", "r", stdin);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	cin >> n >> m >> k;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	for (int i = 0; i < n; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		for (int j = 0; j < n; j++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                			int x; cin >> x;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            			if (x > 0) gun_grid[i][j].push_back(x);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	for (int i = 1; i <= m; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		int x, y, d, s; cin >> x >> y >> d >> s;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		x--; y--;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		player_x[i] = x;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		player_y[i] = y;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		player_d[i] = d;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		player_s[i] = s;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		player_g[i] = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		score[i] = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	//print();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	for (int turn = 1; turn <= k; turn++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		moveAllPlayer();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		//print();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	for (int i = 1; i <= m; i++) cout << score[i] << " ";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	return 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }