#define _CRT_SECURE_NO_WARNINGS
#include <iostream>
#include <queue>
using namespace std;

const int GRIDSIZE = 70;

int R, C, K;

int grid[GRIDSIZE + 3 + 10][GRIDSIZE + 10];
int exit_pos[GRIDSIZE + 3 + 10][GRIDSIZE + 10];

bool visited[GRIDSIZE + 3 + 10][GRIDSIZE + 10];
int ans;

int dx[4] = { -1,0,1,0 };
int dy[4] = { 0,1,0,-1 };

void print() {
	cout << "grid" << "\n";
    	for (int i = 0; i < R + 3; i++) {
        		for (int j = 0; j < C; j++) {
                			cout << grid[i][j] << " ";
                            		}
                                    		cout << "\n";
                                            	}
                                                	cout << "\n";

                                                    	cout << "exit_pos" << "\n";
                                                        	for (int i = 0; i < R + 3; i++) {
                                                            		for (int j = 0; j < C; j++) {
                                                                    			cout << exit_pos[i][j] << " ";
                                                                                		}
                                                                                        		cout << "\n";
                                                                                                	}
                                                                                                    	cout << "\n";
                                                                                                        }

                                                                                                        void initGrid() {
                                                                                                        	for (int i = 0; i < R + 3; i++) {
                                                                                                            		for (int j = 0; j < C; j++) {
                                                                                                                    			grid[i][j] = 0;
                                                                                                                                		}
                                                                                                                                        	}

                                                                                                                                            	for (int i = 0; i < R + 3; i++) {
                                                                                                                                                		for (int j = 0; j < C; j++) {
                                                                                                                                                        			exit_pos[i][j] = 0;
                                                                                                                                                                    		}
                                                                                                                                                                            	}
                                                                                                                                                                                }

                                                                                                                                                                                bool inRange(int x, int y) {
                                                                                                                                                                                	return (x >= 0 && x < R + 3 && y >= 0 && y < C);
                                                                                                                                                                                    }

                                                                                                                                                                                    bool downPossible(int x, int y) {
                                                                                                                                                                                    	if (!inRange(x + 1, y - 1) || grid[x + 1][y - 1] != 0) return false; // 격자 범위 체크 안함
                                                                                                                                                                                        	if (!inRange(x + 2, y) || grid[x + 2][y] != 0) return false;
                                                                                                                                                                                            	if (!inRange(x + 1, y + 1) || grid[x + 1][y + 1] != 0) return false;
                                                                                                                                                                                                	return true;
                                                                                                                                                                                                    }

                                                                                                                                                                                                    bool leftPossible(int x, int y) {
                                                                                                                                                                                                    	if (!inRange(x - 1, y - 1) || grid[x - 1][y - 1] != 0) return false;
                                                                                                                                                                                                        	if (!inRange(x, y - 2) || grid[x][y - 2] != 0) return false;
                                                                                                                                                                                                            	if (!inRange(x + 1, y - 1) || grid[x + 1][y - 1] != 0) return false;
                                                                                                                                                                                                                	return true;
                                                                                                                                                                                                                    }

                                                                                                                                                                                                                    bool rightPossible(int x, int y) {
                                                                                                                                                                                                                    	if (!inRange(x - 1, y + 1) || grid[x - 1][y + 1] != 0) return false;
                                                                                                                                                                                                                        	if (!inRange(x, y + 2) || grid[x][y + 2] != 0) return false;
                                                                                                                                                                                                                            	if (!inRange(x + 1, y + 1) || grid[x + 1][y + 1] != 0) return false;
                                                                                                                                                                                                                                	return true;
                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                    void moveFairy(int x, int y, int id) {
                                                                                                                                                                                                                                    	for (int i = 0; i < R + 3; i++) {
                                                                                                                                                                                                                                        		for (int j = 0; j < C; j++) {
                                                                                                                                                                                                                                                			visited[i][j] = false;
                                                                                                                                                                                                                                                            		}
                                                                                                                                                                                                                                                                    	}
                                                                                                                                                                                                                                                                        	queue<pair<int, int>> q;

                                                                                                                                                                                                                                                                            	int max_row = x;

                                                                                                                                                                                                                                                                                	q.push({ x, y });
                                                                                                                                                                                                                                                                                    	visited[x][y] = true;
                                                                                                                                                                                                                                                                                        	while (!q.empty()) {
                                                                                                                                                                                                                                                                                            		int cx = q.front().first;
                                                                                                                                                                                                                                                                                                    		int cy = q.front().second;
                                                                                                                                                                                                                                                                                                            		q.pop();

                                                                                                                                                                                                                                                                                                                    		if (max_row < cx) max_row = cx;

                                                                                                                                                                                                                                                                                                                            		for (int dir = 0; dir < 4; dir++) {
                                                                                                                                                                                                                                                                                                                                    			int nx = cx + dx[dir];
                                                                                                                                                                                                                                                                                                                                                			int ny = cy + dy[dir];

                                                                                                                                                                                                                                                                                                                                                            			if (inRange(nx, ny) && !visited[nx][ny] && ((grid[nx][ny] == grid[cx][cy]) || (grid[nx][ny] != 0 && exit_pos[cx][cy] == 1))) {
                                                                                                                                                                                                                                                                                                                                                                        				q.push({ nx, ny });
                                                                                                                                                                                                                                                                                                                                                                                        				visited[nx][ny] = true;
                                                                                                                                                                                                                                                                                                                                                                                                        			}
                                                                                                                                                                                                                                                                                                                                                                                                                    		}
                                                                                                                                                                                                                                                                                                                                                                                                                            	}

                                                                                                                                                                                                                                                                                                                                                                                                                                	ans += (max_row - 2);
                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                    void moveCross(int id, int start_col, int exit_d) {
                                                                                                                                                                                                                                                                                                                                                                                                                                    	int cur_row = 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                        	int cur_col = start_col;
                                                                                                                                                                                                                                                                                                                                                                                                                                            	int cur_d = exit_d;

                                                                                                                                                                                                                                                                                                                                                                                                                                                	while(1){ // while문 쓰자
                                                                                                                                                                                                                                                                                                                                                                                                                                                    		if (downPossible(cur_row, cur_col)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            			cur_row++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		else if (leftPossible(cur_row, cur_col) && downPossible(cur_row, cur_col - 1)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        			cur_col--;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    			cur_row++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                			cur_d = (cur_d + 3) % 4;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		else if (rightPossible(cur_row, cur_col) && downPossible(cur_row, cur_col + 1)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            			cur_col++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        			cur_row++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    			cur_d = (cur_d + 1) % 4;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		else break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	if (cur_row >= 1 && cur_row <= 3) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		initGrid();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	grid[cur_row][cur_col] = id;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	exit_pos[cur_row + dx[cur_d]][cur_col + dy[cur_d]] = 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	for (int dir = 0; dir < 4; dir++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		int nx = cur_row + dx[dir];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		int ny = cur_col + dy[dir];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		grid[nx][ny] = id;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	// 정령의 이동
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	moveFairy(cur_row, cur_col, id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            int main() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	ios::sync_with_stdio(0); cin.tie(0); cout.tie(0);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	//freopen("sample_input.txt", "r", stdin);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	cin >> R >> C >> K;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	ans = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	initGrid();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	for (int i = 1; i <= K; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		//cout << i << "번 골렘 출발" << "\n";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		int start_col, exit_d; cin >> start_col >> exit_d;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		start_col--;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		moveCross(i, start_col, exit_d);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		//print();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	cout << ans << "\n";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	return 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }