/*
격자 : n x n
격자의 숫자들은 지역별 인구수

기울어진 직사각형 : 격자 내에 있는 한 지점으로부터 체스의 비숍처럼 대각선으로 움직이며 반시계 순회를 했을 때 지나왔던 지점들의 집합
반드시 아래에서 시작해서 1, 2, 3, 4번 방향순으로 순회해야하며 각 방향으로 최소 1번은 움직여야 함
또한 이동하는 도중 격자 밖으로 넘어가면 안됨

1번 부족은 기울어진 직사각형의 경계와 그 안에 있는 지역을 가짐
기울어진 직사각형의 꼭짓점은 상하좌우로 4가지가 존재하고, 이루는 경계선 또한 4가지가 존재
이러한 꼭짓점과 선을 기준으로 나머지 부족이 갖는 지역이 결정

2번 부족은 기울어진 직사각형 좌측 상단 경계의 윗부분에 해당하는 지역을 가짐
이때 위쪽 꼭짓점의 위에 있는 칸들은 모두 포함하지만 왼쪽 꼭짓점의 왼쪽에 있는 칸들은 포함하지 않음

3번 부족은 기울어진 직사각형의 우측 상단 경계의 윗부분에 해당하는 지역을 가짐
이때 오른쪽 꼭짓점의 오른쪽에 있는 칸들은 모두 포함하지만 윗쪽 꼭짓점의 위쪽에 있는 칸들은 포함하지 않음

4번 부족은 기울어진 직사각형의 좌측 하단 경계의 아랫부분에 해당하는 지역을 가짐
이때 왼쪽 꼭짓점의 왼쪽에 있는 칸들은 모두 포함하지만 아랫쪽 꼭짓점의 아래쪽에 있는 칸들은 포함하지 않음

5번 부족은 기울어진 직사각형의 우측 하단 경계의 아랫부분에 해당하는 지역을 가짐
이때 아랫쪽 꼭짓점의 아랫쪽에 있는 칸들은 모두 포함하지만 오른쪽 꼭짓점의 오른쪽에 있는 칸들은 포함하지 않음

각 부족장이 관리하는 인구 수의 최댓값과 최솟값의 차이가 가장 최소가 되는 것으로 경계를 정하고자 함

초기 나라의 인구 정보가 주어졌을 때 각 부족장이 관리하는 인구 수의 최댓값과 최솟값의 차이가 가장 작은 때의 값을 계산
*/
#define _CRT_SECURE_NO_WARNINGS
#include <iostream>
#include <algorithm>
using namespace std;

const int MAXN = 20;
const int FIVE = 5;

int n;
int grid[MAXN + 10][MAXN + 10];
int boarder[MAXN + 10][MAXN + 10];
int population[FIVE + 10];
int total_population;
int ans = 1e9;

void print() {
	cout << "grid" << "\n";
    	for (int i = 0; i < n; i++) {
        		for (int j = 0; j < n; j++) {
                			cout << grid[i][j] << " ";
                            		}
                                    		cout << "\n";
                                            	}
                                                	cout << "\n";
                                                    }

                                                    bool inRange(int x, int y) {
                                                    	return (x >= 0 && x < n && y >= 0 && y < n);
                                                        }

                                                        bool isPossible(int x, int y, int k, int l) {
                                                        	return (inRange(x - k, y + k) && inRange(x - k - l, y + k - l) && inRange(x - l , y - l));
                                                            }

                                                            void makeBoarder(int x, int y, int k, int l) {
                                                            	for (int i = 0; i < n; i++) {
                                                                		for (int j = 0; j < n; j++) {
                                                                        			boarder[i][j] = 0;
                                                                                    		}
                                                                                            	}

                                                                                                	int dx[4] = {-1,-1,1,1};
                                                                                                    	int dy[4] = {1,-1,-1,1};

                                                                                                        	boarder[x][y] = 1;
                                                                                                            	for (int i = 0; i < k; i++) {
                                                                                                                		x += dx[0];
                                                                                                                        		y += dy[0];
                                                                                                                                		boarder[x][y] = 1;
                                                                                                                                        	}

                                                                                                                                            	for (int i = 0; i < l; i++) {
                                                                                                                                                		x += dx[1];
                                                                                                                                                        		y += dy[1];
                                                                                                                                                                		boarder[x][y] = 1;
                                                                                                                                                                        	}

                                                                                                                                                                            	for (int i = 0; i < k; i++) {
                                                                                                                                                                                		x += dx[2];
                                                                                                                                                                                        		y += dy[2];
                                                                                                                                                                                                		boarder[x][y] = 1;
                                                                                                                                                                                                        	}

                                                                                                                                                                                                            	for (int i = 0; i < l; i++) {
                                                                                                                                                                                                                		x += dx[3];
                                                                                                                                                                                                                        		y += dy[3];
                                                                                                                                                                                                                                		boarder[x][y] = 1;
                                                                                                                                                                                                                                        	}

                                                                                                                                                                                                                                            	/*
                                                                                                                                                                                                                                                	cout << "boarder" << "\n";
                                                                                                                                                                                                                                                    	for (int i = 0; i < n; i++) {
                                                                                                                                                                                                                                                        		for (int j = 0; j < n; j++) {
                                                                                                                                                                                                                                                                			cout << boarder[i][j] << " ";
                                                                                                                                                                                                                                                                            		}
                                                                                                                                                                                                                                                                                    		cout << "\n";
                                                                                                                                                                                                                                                                                            	}
                                                                                                                                                                                                                                                                                                	cout << "\n";
                                                                                                                                                                                                                                                                                                    	*/
                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                        int getScore(int x, int y, int k, int l) {

                                                                                                                                                                                                                                                                                                        	makeBoarder(x, y, k, l);
                                                                                                                                                                                                                                                                                                            	for (int i = 1; i <= 5; i++) {
                                                                                                                                                                                                                                                                                                                		population[i] = 0;
                                                                                                                                                                                                                                                                                                                        	}

                                                                                                                                                                                                                                                                                                                            	// 좌측 상단
                                                                                                                                                                                                                                                                                                                                	for (int i = 0; i < x - l; i++) {
                                                                                                                                                                                                                                                                                                                                    		for (int j = 0; j <= y + k - l && boarder[i][j] == 0; j++) {
                                                                                                                                                                                                                                                                                                                                            			population[2] += grid[i][j];
                                                                                                                                                                                                                                                                                                                                                        		}
                                                                                                                                                                                                                                                                                                                                                                	}

                                                                                                                                                                                                                                                                                                                                                                    	// 우측 상단
                                                                                                                                                                                                                                                                                                                                                                        	for (int i = 0; i <= x - k; i++) {
                                                                                                                                                                                                                                                                                                                                                                            		for (int j = n - 1; j >= y + k - l + 1 && boarder[i][j] == 0; j--) {
                                                                                                                                                                                                                                                                                                                                                                                    			population[3] += grid[i][j];
                                                                                                                                                                                                                                                                                                                                                                                                		}
                                                                                                                                                                                                                                                                                                                                                                                                        	}

                                                                                                                                                                                                                                                                                                                                                                                                            	// 좌측 하단
                                                                                                                                                                                                                                                                                                                                                                                                                	for (int i = x - l; i < n; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                    		for (int j = 0; j < y && boarder[i][j] == 0; j++) {
                                                                                                                                                                                                                                                                                                                                                                                                                            			population[4] += grid[i][j];
                                                                                                                                                                                                                                                                                                                                                                                                                                        		}
                                                                                                                                                                                                                                                                                                                                                                                                                                                	}

                                                                                                                                                                                                                                                                                                                                                                                                                                                    	// 우측 하단
                                                                                                                                                                                                                                                                                                                                                                                                                                                        	for (int i = x - k + 1; i < n; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            		for (int j = n - 1; j >= y && boarder[i][j] == 0; j--) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    			population[5] += grid[i][j];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	population[1] = total_population;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	for (int i = 2; i <= 5; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		population[1] -= population[i];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	int max_p = -1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	int min_p = total_population;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	for (int i = 1; i <= 5; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		if (max_p < population[i]) max_p = population[i];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	for (int i = 1; i <= 5; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		if (min_p > population[i]) min_p = population[i];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	return max_p - min_p;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                int main() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	ios::sync_with_stdio(0); cin.tie(0); cout.tie(0);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	//freopen("sample_input.txt", "r", stdin);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	cin >> n;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	for (int i = 0; i < n; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		for (int j = 0; j < n; j++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        			cin >> grid[i][j];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    			total_population += grid[i][j];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	for (int x = 2; x < n; x++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		for (int y = 1; y < n - 1; y++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        			for (int k = 1; k <= n / 2; k++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    				for (int l = 1; l <= n / 2; l++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    					if (isPossible(x, y, k, l)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        						ans = min(ans, getScore(x, y, k, l));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                					}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    				}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    			}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	cout << ans << "\n";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	return 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }