#define _CRT_SECURE_NO_WARNINGS
#include <iostream>
#include <algorithm>
using namespace std;

const int MAXN = 20;
const int FIVE = 5;

int n;
int grid[MAXN + 10][MAXN + 10];
int boarder[MAXN + 10][MAXN + 10];
int population[FIVE + 10];
int total_population;
int ans;

void print() {
	cout << "grid" << "\n";
    	for (int i = 0; i < n; i++) {
        		for (int j = 0; j < n; j++) {
                			cout << grid[i][j] << " ";
                            		}
                                    		cout << "\n";
                                            	}
                                                	cout << "\n";
                                                    }

                                                    bool inRange(int x, int y) {
                                                    	return (x >= 0 && x < n && y >= 0 && y < n);
                                                        }

                                                        bool isPossible(int x, int y, int k, int l) {
                                                        	return (inRange(x - k, y + k) && inRange(x - k - l, y + k - l) && inRange(x - l , y - l));
                                                            }

                                                            void makeBoarder(int x, int y, int k, int l) {
                                                            	for (int i = 0; i < n; i++) {
                                                                		for (int j = 0; j < n; j++) {
                                                                        			boarder[i][j] = 0;
                                                                                    		}
                                                                                            	}

                                                                                                	int dx[4] = {-1,-1,1,1};
                                                                                                    	int dy[4] = {1,-1,-1,1};

                                                                                                        	boarder[x][y] = 1;
                                                                                                            	for (int i = 0; i < k; i++) {
                                                                                                                		x += dx[0];
                                                                                                                        		y += dy[0];
                                                                                                                                		boarder[x][y] = 1;
                                                                                                                                        	}

                                                                                                                                            	for (int i = 0; i < l; i++) {
                                                                                                                                                		x += dx[1];
                                                                                                                                                        		y += dy[1];
                                                                                                                                                                		boarder[x][y] = 1;
                                                                                                                                                                        	}

                                                                                                                                                                            	for (int i = 0; i < k; i++) {
                                                                                                                                                                                		x += dx[2];
                                                                                                                                                                                        		y += dy[2];
                                                                                                                                                                                                		boarder[x][y] = 1;
                                                                                                                                                                                                        	}

                                                                                                                                                                                                            	for (int i = 0; i < l; i++) {
                                                                                                                                                                                                                		x += dx[3];
                                                                                                                                                                                                                        		y += dy[3];
                                                                                                                                                                                                                                		boarder[x][y] = 1;
                                                                                                                                                                                                                                        	}

                                                                                                                                                                                                                                            	/*
                                                                                                                                                                                                                                                	cout << "boarder" << "\n";
                                                                                                                                                                                                                                                    	for (int i = 0; i < n; i++) {
                                                                                                                                                                                                                                                        		for (int j = 0; j < n; j++) {
                                                                                                                                                                                                                                                                			cout << boarder[i][j] << " ";
                                                                                                                                                                                                                                                                            		}
                                                                                                                                                                                                                                                                                    		cout << "\n";
                                                                                                                                                                                                                                                                                            	}
                                                                                                                                                                                                                                                                                                	cout << "\n";
                                                                                                                                                                                                                                                                                                    	*/
                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                        int getScore(int x, int y, int k, int l) {

                                                                                                                                                                                                                                                                                                        	makeBoarder(x, y, k, l);
                                                                                                                                                                                                                                                                                                            	for (int i = 1; i <= 5; i++) {
                                                                                                                                                                                                                                                                                                                		population[i] = 0;
                                                                                                                                                                                                                                                                                                                        	}

                                                                                                                                                                                                                                                                                                                            	// 좌측 상단
                                                                                                                                                                                                                                                                                                                                	for (int i = 0; i < x - l; i++) {
                                                                                                                                                                                                                                                                                                                                    		for (int j = 0; j <= y + k - l && boarder[i][j] == 0; j++) {
                                                                                                                                                                                                                                                                                                                                            			population[2] += grid[i][j];
                                                                                                                                                                                                                                                                                                                                                        		}
                                                                                                                                                                                                                                                                                                                                                                	}

                                                                                                                                                                                                                                                                                                                                                                    	// 우측 상단
                                                                                                                                                                                                                                                                                                                                                                        	for (int i = 0; i <= x - k; i++) {
                                                                                                                                                                                                                                                                                                                                                                            		for (int j = n - 1; j >= y + k - l + 1 && boarder[i][j] == 0; j--) {
                                                                                                                                                                                                                                                                                                                                                                                    			population[3] += grid[i][j];
                                                                                                                                                                                                                                                                                                                                                                                                		}
                                                                                                                                                                                                                                                                                                                                                                                                        	}

                                                                                                                                                                                                                                                                                                                                                                                                            	// 좌측 하단
                                                                                                                                                                                                                                                                                                                                                                                                                	for (int i = x - l; i < n; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                    		for (int j = 0; j < y && boarder[i][j] == 0; j++) {
                                                                                                                                                                                                                                                                                                                                                                                                                            			population[4] += grid[i][j];
                                                                                                                                                                                                                                                                                                                                                                                                                                        		}
                                                                                                                                                                                                                                                                                                                                                                                                                                                	}

                                                                                                                                                                                                                                                                                                                                                                                                                                                    	// 우측 하단
                                                                                                                                                                                                                                                                                                                                                                                                                                                        	for (int i = x - k + 1; i < n; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            		for (int j = n - 1; j >= y && boarder[i][j] == 0; j--) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    			population[5] += grid[i][j];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	population[1] = total_population;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	for (int i = 2; i <= 5; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		population[1] -= population[i];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	int max_p = -1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	int min_p = total_population;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	for (int i = 1; i <= 5; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		if (max_p < population[i]) max_p = population[i];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	for (int i = 1; i <= 5; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		if (min_p > population[i]) min_p = population[i];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	return max_p - min_p;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                int main() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	ios::sync_with_stdio(0); cin.tie(0); cout.tie(0);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	//freopen("sample_input.txt", "r", stdin);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	cin >> n;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	for (int i = 0; i < n; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		for (int j = 0; j < n; j++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        			cin >> grid[i][j];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    			total_population += grid[i][j];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	ans = 1e9;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	for (int x = 0; x < n; x++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		for (int y = 0; y < n; y++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            			for (int k = 1; k <= n; k++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        				for (int l = 1; l <= n; l++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        					if (isPossible(x, y, k, l)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            						ans = min(ans, getScore(x, y, k, l));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    					}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        				}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        			}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	cout << ans << "\n";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	return 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }