#define _CRT_SECURE_NO_WARNINGS
#include <iostream>
#include <queue>
#include <tuple>
using namespace std;

const int GRIDSIZE = 10;

struct State {
	int rx;
    	int ry;
        	int bx;
            	int by;
                	int cnt;
                    };

                    int N, M;
                    int rx, ry;
                    int bx, by;
                    int grid[GRIDSIZE + 10][GRIDSIZE + 10];
                    bool redGoal;
                    bool blueGoal;

                    int dx[4] = { 0,1,0,-1 };
                    int dy[4] = { 1,0,-1,0 };

                    void print() {
                    	cout << "grid" << "\n";
                        	for (int i = 0; i < N; i++) {
                            		for (int j = 0; j < M; j++) {
                                    			cout << grid[i][j] << " ";
                                                		}
                                                        		cout << "\n";
                                                                	}
                                                                    	cout << "\n";

                                                                        	cout << "RED : " << rx << " " << ry << "\n";
                                                                            	cout << "BLUE : " << bx << " " << by << "\n";
                                                                                }

                                                                                pair<int, int> moveRed(int x, int y, int d) {
                                                                                	while (1) {
                                                                                    		x += dx[d];
                                                                                            		y += dy[d];

                                                                                                    		if (grid[x][y] == 1) redGoal = true;
                                                                                                            		if (grid[x][y] == -1) return { x - dx[d], y - dy[d]};
                                                                                                                    	}
                                                                                                                        }

                                                                                                                        pair<int, int> moveBlue(int x, int y, int d) {
                                                                                                                        	while (1) {
                                                                                                                            		x += dx[d];
                                                                                                                                    		y += dy[d];

                                                                                                                                            		if (grid[x][y] == 1) blueGoal = true;
                                                                                                                                                    		if (grid[x][y] == -1) return { x - dx[d], y - dy[d]};
                                                                                                                                                            	}
                                                                                                                                                                }

                                                                                                                                                                bool redFirst(int rx, int ry, int bx, int by, int dir) {
                                                                                                                                                                	if (dir == 0 && rx == bx && by < ry) return true;
                                                                                                                                                                    	if (dir == 1 && ry == by && bx < rx) return true;
                                                                                                                                                                        	if (dir == 2 && rx == bx && ry < by) return true;
                                                                                                                                                                            	if (dir == 3 && ry == by && rx < bx) return true;
                                                                                                                                                                                	else return false;
                                                                                                                                                                                    }

                                                                                                                                                                                    int main() {
                                                                                                                                                                                    	ios::sync_with_stdio(0); cin.tie(0); cout.tie(0);
                                                                                                                                                                                        	//freopen("sample_input.txt", "r", stdin);

                                                                                                                                                                                            	cin >> N >> M;
                                                                                                                                                                                                	for (int i = 0; i < N; i++) {
                                                                                                                                                                                                    		for (int j = 0; j < M; j++) {
                                                                                                                                                                                                            			char x; cin >> x;
                                                                                                                                                                                                                        			if (x == '.') grid[i][j] = 0;
                                                                                                                                                                                                                                    			else if (x == '#') grid[i][j] = -1;
                                                                                                                                                                                                                                                			else if (x == 'B') {
                                                                                                                                                                                                                                                            				grid[i][j] = 0;
                                                                                                                                                                                                                                                                            				bx = i;
                                                                                                                                                                                                                                                                                            				by = j;
                                                                                                                                                                                                                                                                                                            			}
                                                                                                                                                                                                                                                                                                                        			else if (x == 'R') {
                                                                                                                                                                                                                                                                                                                                    				grid[i][j] = 0;
                                                                                                                                                                                                                                                                                                                                                    				rx = i;
                                                                                                                                                                                                                                                                                                                                                                    				ry = j;
                                                                                                                                                                                                                                                                                                                                                                                    			}
                                                                                                                                                                                                                                                                                                                                                                                                			else if (x == 'O') grid[i][j] = 1;
                                                                                                                                                                                                                                                                                                                                                                                                            		}
                                                                                                                                                                                                                                                                                                                                                                                                                    	}

                                                                                                                                                                                                                                                                                                                                                                                                                        	//print();
                                                                                                                                                                                                                                                                                                                                                                                                                            	queue<State> q;
                                                                                                                                                                                                                                                                                                                                                                                                                                	q.push({ rx, ry, bx, by, 0 });
                                                                                                                                                                                                                                                                                                                                                                                                                                    	while (!q.empty()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                        		State cur = q.front();
                                                                                                                                                                                                                                                                                                                                                                                                                                                		q.pop();

                                                                                                                                                                                                                                                                                                                                                                                                                                                        		if (cur.cnt >= 10) continue;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                		for (int dir = 0; dir < 4; dir++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        			int nrx, nry, nbx, nby;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    			redGoal = false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                			blueGoal = false;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            			tie(nrx, nry) = moveRed(cur.rx, cur.ry, dir);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        			tie(nbx, nby) = moveBlue(cur.bx, cur.by, dir);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    			
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                			if (nrx == nbx && nry == nby) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            				if (redFirst(cur.rx, cur.ry, cur.bx, cur.by, dir)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            					nbx -= dx[dir];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                					nby -= dy[dir];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    				}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    				else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    					nrx -= dx[dir];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        					nry -= dy[dir];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            				}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            			}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        			if (redGoal && !blueGoal) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    				cout << cur.cnt + 1 << "\n";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    				return 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    			}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                			if (!redGoal && !blueGoal && (cur.rx != nrx || cur.ry != nry || cur.bx != nbx || cur.by != nby)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            				q.push({ nrx, nry, nbx, nby, cur.cnt + 1 });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            			}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	cout << -1 << "\n";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	return 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }