/*
격자 : n x n
플레이어 : m개, 각각 격자칸에서 한 자리를 차지, 방향
독점계약

턴이 한 번 진행될 때 각 플레이어들은 한 칸씩 이동
해당 칸에 이동했을 때 플레이어는 해당 칸을 독점 계약
초기 상태에 위치한 땅 역시 해당 플레이어의 독점 계약한 칸

독점 계약은 k만큼의 턴 동안만 유효. k턴이 지나게 되면 해당 칸은 다시 주인이 없는 칸으로 돌아가게 됨

각 플레이어는 각 방향별로 이동 우선순위를 가짐
우선 플레이어는 본인에게 인접한 상하좌우 4칸 중 아무도 독점계약을 맺지 않는 칸으로 이동
만약 그러한 칸이 없을 경우에는 인접한 4방향 중 본인이 독점계약한 땅으로 이동
이때 이동할 수 있는 칸이 여러개일 수 있음으로 이동 우선순위에 따라 움직일 칸을 결정
플레이어가 보고 있는 방향은 그 직전에 이동한 방향

모든 플레이어가 이동한 후 한 칸에 여러 플레이어가 있을 경우에는 (가장 작은 번호를 가진 플레이어만 살아남)고
나머지 플레이어는 게임에서 사라지게 됨

이 과정이 계속 반복될 때 1번 플레이어만 살아남기까지 걸린 턴의 수를 출력
답이 1000 이상이거나 불가능한 경우에는 -1을 출력
*/
#define _CRT_SECURE_NO_WARNINGS
#include <iostream>
using namespace std;

const int MAXN = 20;
const int MAXM = 400;
const pair<int, int> OUTOFGRID = { -1, -1 };

int n, m, k;

pair<int, int> p_pos[MAXM + 10];
int p_dir[MAXM + 10];
pair<int, int> contract[MAXN + 10][MAXN + 10];
int prior_dir[MAXM + 10][4][4];

int dx[4] = { -1,1,0,0 };
int dy[4] = { 0,0,-1,1 };

int print_grid[MAXN + 10][MAXN + 10];

void print() {
	for (int i = 0; i < n; i++) {
    		for (int j = 0; j < n; j++) {
            			print_grid[i][j] = 0;
                        		}
                                	}

                                    	cout << "p_pos" << "\n";
                                        	for (int i = 1; i <= m; i++) {
                                            		int cx = p_pos[i].first;
                                                    		int cy = p_pos[i].second;
                                                            		print_grid[cx][cy] = i;
                                                                    	}
                                                                        	for (int i = 0; i < n; i++) {
                                                                            		for (int j = 0; j < n; j++) {
                                                                                    			cout << print_grid[i][j] << " ";
                                                                                                		}
                                                                                                        		cout << "\n";
                                                                                                                	}
                                                                                                                    	cout << "\n";

                                                                                                                        	cout << "p_dir" << "\n";
                                                                                                                            	for (int i = 1; i <= m; i++) {
                                                                                                                                		cout << i << " : " << p_dir[i] << "\n";
                                                                                                                                        	}
                                                                                                                                            	cout << "\n";

                                                                                                                                                	cout << "contract" << "\n";
                                                                                                                                                    	for (int i = 0; i < n; i++) {
                                                                                                                                                        		for (int j = 0; j < n; j++) {
                                                                                                                                                                			cout << "{ ";
                                                                                                                                                                            			cout << contract[i][j].first << " " << contract[i][j].second;
                                                                                                                                                                                        			cout << " }";
                                                                                                                                                                                                    		}
                                                                                                                                                                                                            		cout << "\n";
                                                                                                                                                                                                                    	}
                                                                                                                                                                                                                        	cout << "\n";
                                                                                                                                                                                                                            }

                                                                                                                                                                                                                            bool isOver() {
                                                                                                                                                                                                                            	for (int i = 2; i <= m; i++) {
                                                                                                                                                                                                                                		if (p_pos[i] != OUTOFGRID) return false;
                                                                                                                                                                                                                                        	}
                                                                                                                                                                                                                                            	return true;
                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                bool inRange(int x, int y) {
                                                                                                                                                                                                                                                	return (x >= 0 && x < n && y >= 0 && y < n);
                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                    /*
                                                                                                                                                                                                                                                    턴이 한 번 진행될 때 각 플레이어들은 한 칸씩 이동
                                                                                                                                                                                                                                                    해당 칸에 이동했을 때 플레이어는 해당 칸을 독점 계약
                                                                                                                                                                                                                                                    초기 상태에 위치한 땅 역시 해당 플레이어의 독점 계약한 칸

                                                                                                                                                                                                                                                    독점 계약은 k만큼의 턴 동안만 유효. k턴이 지나게 되면 해당 칸은 다시 주인이 없는 칸으로 돌아가게 됨

                                                                                                                                                                                                                                                    각 플레이어는 각 방향별로 이동 우선순위를 가짐
                                                                                                                                                                                                                                                    우선 플레이어는 본인에게 인접한 상하좌우 4칸 중 아무도 독점계약을 맺지 않는 칸으로 이동
                                                                                                                                                                                                                                                    만약 그러한 칸이 없을 경우에는 인접한 4방향 중 본인이 독점계약한 땅으로 이동
                                                                                                                                                                                                                                                    이때 이동할 수 있는 칸이 여러개일 수 있음으로 이동 우선순위에 따라 움직일 칸을 결정
                                                                                                                                                                                                                                                    플레이어가 보고 있는 방향은 그 직전에 이동한 방향

                                                                                                                                                                                                                                                    모든 플레이어가 이동한 후 한 칸에 여러 플레이어가 있을 경우에는 (가장 작은 번호를 가진 플레이어만 살아남)고
                                                                                                                                                                                                                                                    나머지 플레이어는 게임에서 사라지게 됨

                                                                                                                                                                                                                                                    이 과정이 계속 반복될 때 1번 플레이어만 살아남기까지 걸린 턴의 수를 출력
                                                                                                                                                                                                                                                    답이 1000 이상이거나 불가능한 경우에는 -1을 출력
                                                                                                                                                                                                                                                    */
                                                                                                                                                                                                                                                    void moveAllPlayer() {
                                                                                                                                                                                                                                                    	for (int i = 1; i <= m; i++) {
                                                                                                                                                                                                                                                        		if (p_pos[i] == OUTOFGRID) continue;

                                                                                                                                                                                                                                                                		int cx = p_pos[i].first;
                                                                                                                                                                                                                                                                        		int cy = p_pos[i].second;
                                                                                                                                                                                                                                                                                		int cd = p_dir[i];

                                                                                                                                                                                                                                                                                        		bool moved = false;
                                                                                                                                                                                                                                                                                                		for (int order = 0; order < 4; order++) {
                                                                                                                                                                                                                                                                                                        			int nd = prior_dir[i][cd][order];
                                                                                                                                                                                                                                                                                                                    			int nx = cx + dx[nd];
                                                                                                                                                                                                                                                                                                                                			int ny = cy + dy[nd];

                                                                                                                                                                                                                                                                                                                                            			if (inRange(nx, ny) && contract[nx][ny].first == 0) {
                                                                                                                                                                                                                                                                                                                                                        				p_pos[i].first = nx;
                                                                                                                                                                                                                                                                                                                                                                        				p_pos[i].second = ny;
                                                                                                                                                                                                                                                                                                                                                                                        				p_dir[i] = nd;
                                                                                                                                                                                                                                                                                                                                                                                                        				moved = true;
                                                                                                                                                                                                                                                                                                                                                                                                                        				break;
                                                                                                                                                                                                                                                                                                                                                                                                                                        			}
                                                                                                                                                                                                                                                                                                                                                                                                                                                    		}

                                                                                                                                                                                                                                                                                                                                                                                                                                                            		if (!moved) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    			for (int order = 0; order < 4; order++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                				int nd = prior_dir[i][cd][order];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                				int nx = cx + dx[nd];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                				int ny = cy + dy[nd];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                				if (inRange(nx, ny) && contract[nx][ny].first == i) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                					p_pos[i].first = nx;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    					p_pos[i].second = ny;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        					p_dir[i] = nd;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            					moved = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                					break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    				}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    			}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	// 공통 위치 지우고
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	for (int i = 1; i < m; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		for (int j = i + 1; j <= m; j++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            			if (p_pos[i] == OUTOFGRID) continue;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        			if (p_pos[i] == p_pos[j]) p_pos[j] = OUTOFGRID;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	// 계약 표시
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	for (int i = 1; i <= m; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		if (p_pos[i] == OUTOFGRID) continue;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		int cx = p_pos[i].first;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		int cy = p_pos[i].second;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		contract[cx][cy] = { i, k + 1};
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            void reduceContract() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	for (int i = 0; i < n; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		for (int j = 0; j < n; j++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        			if (contract[i][j].first == 0) continue;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    			if (contract[i][j].second == 1) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                				contract[i][j].first = 0;;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                				contract[i][j].second = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                			}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            			else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        				contract[i][j].second--;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        			}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                int main() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	ios::sync_with_stdio(0); cin.tie(0); cout.tie(0);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	//freopen("sample_input.txt", "r", stdin);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	cin >> n >> m >> k;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	for (int i = 0; i < n; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		for (int j = 0; j < n; j++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        			int x; cin >> x;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    			if (x != 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                				p_pos[x] = { i, j };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                				contract[i][j] = { x, k };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                			}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            			
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	for (int i = 1; i <= m; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		int d; cin >> d; d--;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		p_dir[i] = d;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	for (int i = 1; i <= m; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		for (int cur_dir = 0; cur_dir < 4; cur_dir++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        			for (int order = 0; order < 4; order++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    				int d; cin >> d; d--;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    				prior_dir[i][cur_dir][order] = d;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    			}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	//print();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	for (int turn = 1;; turn++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		if (turn >= 1000) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            			cout << -1 << "\n";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        			return 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		//cout << "turn : " << turn << "\n";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		//cout << "moveAllPlayer" << "\n";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		moveAllPlayer();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		//print();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		//cout << "reduceContract" << "\n";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		reduceContract();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		//print();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		if (isOver()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            			cout << turn << "\n";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        			return 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }