/*
사람 : m명
베이스캠프
편의점

1번 사람은 1분에
2번 사람은 2분에
m번 사람은 m분에
각자의 베이스캠프에서 출발하여 편의점으로 이동
사람들은 출발 시간이 되기 전까지 격자 밖에 나와있으며, 사람들이 목표로 하는 편의점은 모두 다름
이 모든 일은 n x n 크기의 격자 위에서 진행

3가지 행동은 총 1분 동안 진행되며, 정확히 1, 2, 3 순서로 진행되어야 함에 유의
1. 격자에 있는 사람들 모두가 본인이 가고 싶은 편의점 방향을 향해서 1칸 움직임
최단거리로 움직이며 최단거리로 움직이는 방법이 여러가지라면 상좌우하 우선순위
최단거리 : 상하좌우 인접한 칸 중 이동가능한 칸으로만 이동하여 도달하기까지 거쳐야 하는 칸의 수가 최소가 되는 거리

2. 만약 편의점에 도착한다면 해당 편의점에서 멈추게 되고, 이때부터 다른 사람들은 해당 편의점이 있는 칸을 지나갈 수 없게 됨
격자에 있는 사람들이 모두 이동한 뒤에 해당 칸을 지나갈 수 없어짐에 유의

3. 현재 시간이 t분이고 t <= m 를 만족한다면, t번 사람은 자신이 가고 싶은 편의점과 가장 가까이 있는 베이스 캠프에 들어감
여기서 가장 가까이에 있다는 뜻 역시 1에서와 같이 최단거리에 해당하는 곳을 의미
가장 가까운 베이스캠프가 여러 가지인 경우에는 그 중 행이 작은 베이스캠프, 행이 같다면 열이 작은 베이스캠프로 들어감
t번 사람이 베이스 캠프로 이동하는 데에는 시간이 전혀 소요되지 않음

이때부터 다른 사람들은 해당 베이스 캠프가 있는 칸을 지나갈 수 없게 됨
t번 사람이 편의점을 향해 움직이기 시작했더라도 해당 베이스 캠프는 앞으로 절대 지나갈 수 없음에 유의
마찬가지로 해당 턴 격자에 있는 사람들이 모두 이동한 뒤에 해당 칸을 지나갈 수 없어짐에 유의

이미 사람들이 도착한 편의점이나 출발한 적이 있는 베이스캠프의 경우 움직일 때 절대 지나갈 수 없는 공간임을 유의
사람들이 위와 같은 방식으로 움직일 때 총 몇 분 후에 모두 편의점에 도착하는지를 구하는 프로그램
*/
#define _CRT_SECURE_NO_WARNINGS
#include <iostream>
#include <vector>
#include <queue>
using namespace std;

const int MAXN = 15;
const int MAXM = 30;
const int INF = 1e9;

int n, m; // 격자의 크기 n, 사람의 수 m

// 이미 사람들이 도착한 편의점이나 출발한 적이 있는 베이스캠프의 경우 움직일 때 절대 지나갈 수 없는 공간임을 유의
int base[MAXN + 10][MAXN + 10]; // 베이스캠프
pair<int, int> player[MAXM + 10];
pair<int, int> conv[MAXM + 10]; // 편의점

int dist[MAXN + 10][MAXN + 10];

int dx[4] = { -1,0,0,1 };
int dy[4] = { 0,-1,1,0 };

void print() {
	cout << "base" << "\n";
    	for (int i = 0; i < n; i++) {
        		for (int j = 0; j < n; j++) {
                			cout << base[i][j] << " ";
                            		}
                                    		cout << "\n";
                                            	}
                                                	cout << "\n";

                                                    	cout << "conv" << "\n";
                                                        	for (int i = 1; i <= m; i++) {
                                                            		cout << i << " : " << conv[i].first << " " << conv[i].second << "\n";
                                                                    	}
                                                                        	cout << "\n";

                                                                            	cout << "player" << "\n";
                                                                                	for (int i = 1; i <= m; i++) {
                                                                                    		cout << i << " : " << player[i].first << " " << player[i].second << "\n";
                                                                                            	}
                                                                                                	cout << "\n";
                                                                                                    }

                                                                                                    bool isOver() {
                                                                                                    	for (int i = 1; i <= m; i++) {
                                                                                                        		if (player[i] != conv[i]) return false;
                                                                                                                	}
                                                                                                                    	return true;
                                                                                                                        }

                                                                                                                        bool inRange(int x, int y) {
                                                                                                                        	return (x >= 0 && x < n && y >= 0 && y < n);
                                                                                                                            }

                                                                                                                            void BFS(int idx) {
                                                                                                                            	for (int i = 0; i < n; i++) {
                                                                                                                                		for (int j = 0; j < n; j++) {
                                                                                                                                        			dist[i][j] = -1;
                                                                                                                                                    		}
                                                                                                                                                            	}
                                                                                                                                                                	queue<pair<int, int>> q;

                                                                                                                                                                    	q.push(conv[idx]);
                                                                                                                                                                        	dist[conv[idx].first][conv[idx].second] = 0;
                                                                                                                                                                            	while (!q.empty()) {
                                                                                                                                                                                		int cx = q.front().first;
                                                                                                                                                                                        		int cy = q.front().second;
                                                                                                                                                                                                		q.pop();

                                                                                                                                                                                                        		for (int dir = 0; dir < 4; dir++) {
                                                                                                                                                                                                                			int nx = cx + dx[dir];
                                                                                                                                                                                                                            			int ny = cy + dy[dir];

                                                                                                                                                                                                                                        			if (inRange(nx, ny) && dist[nx][ny] == -1 && base[nx][ny] != -1) {
                                                                                                                                                                                                                                                    				q.push({ nx, ny });
                                                                                                                                                                                                                                                                    				dist[nx][ny] = dist[cx][cy] + 1;
                                                                                                                                                                                                                                                                                    			}
                                                                                                                                                                                                                                                                                                		}
                                                                                                                                                                                                                                                                                                        	}

                                                                                                                                                                                                                                                                                                            	/*
                                                                                                                                                                                                                                                                                                                	cout << "dist" << "\n";
                                                                                                                                                                                                                                                                                                                    	for (int i = 0; i < n; i++) {
                                                                                                                                                                                                                                                                                                                        		for (int j = 0; j < n; j++) {
                                                                                                                                                                                                                                                                                                                                			cout << dist[i][j] << " ";
                                                                                                                                                                                                                                                                                                                                            		}
                                                                                                                                                                                                                                                                                                                                                    		cout << "\n";
                                                                                                                                                                                                                                                                                                                                                            	}
                                                                                                                                                                                                                                                                                                                                                                	cout << "\n";
                                                                                                                                                                                                                                                                                                                                                                    	*/
                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                        void moveAllPlayer() {
                                                                                                                                                                                                                                                                                                                                                                        	vector<pair<int, int>> v;

                                                                                                                                                                                                                                                                                                                                                                            	for (int i = 1; i <= m; i++) {
                                                                                                                                                                                                                                                                                                                                                                                		if (player[i].first == -1 && player[i].second == -1) continue;
                                                                                                                                                                                                                                                                                                                                                                                        		if (player[i] == conv[i]) continue;

                                                                                                                                                                                                                                                                                                                                                                                                		BFS(i);
                                                                                                                                                                                                                                                                                                                                                                                                        		int min_dist = INF;
                                                                                                                                                                                                                                                                                                                                                                                                                		int min_dir = -1;

                                                                                                                                                                                                                                                                                                                                                                                                                        		for (int dir = 0; dir < 4; dir++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                			int nx = player[i].first + dx[dir]; // 방향을 안 더해줬네 뭐지
                                                                                                                                                                                                                                                                                                                                                                                                                                            			int ny = player[i].second + dy[dir]; // 방향을 안 더해줬네 뭐지

                                                                                                                                                                                                                                                                                                                                                                                                                                                        			if (inRange(nx, ny) && dist[nx][ny] != -1 && min_dist > dist[nx][ny]) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    				min_dist = dist[nx][ny];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    				min_dir = dir;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    			}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		player[i].first += dx[min_dir];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		player[i].second += dy[min_dir];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		if (player[i] == conv[i]) v.push_back(player[i]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	for (int i = 0; i < (int)v.size(); i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		base[v[i].first][v[i].second] = -1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    /*
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    3가지 행동은 총 1분 동안 진행되며, 정확히 1, 2, 3 순서로 진행되어야 함에 유의
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    1. 격자에 있는 사람들 모두가 본인이 가고 싶은 편의점 방향을 향해서 1칸 움직임
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    최단거리로 움직이며 최단거리로 움직이는 방법이 여러가지라면 상좌우하 우선순위
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    최단거리 : 상하좌우 인접한 칸 중 이동가능한 칸으로만 이동하여 도달하기까지 거쳐야 하는 칸의 수가 최소가 되는 거리

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    2. 만약 편의점에 도착한다면 해당 편의점에서 멈추게 되고, 이때부터 다른 사람들은 해당 편의점이 있는 칸을 지나갈 수 없게 됨
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    격자에 있는 사람들이 모두 이동한 뒤에 해당 칸을 지나갈 수 없어짐에 유의

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    3. 현재 시간이 t분이고 t <= m 를 만족한다면, t번 사람은 자신이 가고 싶은 편의점과 가장 가까이 있는 베이스 캠프에 들어감
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    여기서 가장 가까이에 있다는 뜻 역시 1에서와 같이 최단거리에 해당하는 곳을 의미
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    가장 가까운 베이스캠프가 여러 가지인 경우에는 그 중 행이 작은 베이스캠프, 행이 같다면 열이 작은 베이스캠프로 들어감
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    t번 사람이 베이스 캠프로 이동하는 데에는 시간이 전혀 소요되지 않음

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    이때부터 다른 사람들은 해당 베이스 캠프가 있는 칸을 지나갈 수 없게 됨
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    t번 사람이 편의점을 향해 움직이기 시작했더라도 해당 베이스 캠프는 앞으로 절대 지나갈 수 없음에 유의
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    마찬가지로 해당 턴 격자에 있는 사람들이 모두 이동한 뒤에 해당 칸을 지나갈 수 없어짐에 유의

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    이미 사람들이 도착한 편의점이나 출발한 적이 있는 베이스캠프의 경우 움직일 때 절대 지나갈 수 없는 공간임을 유의
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    사람들이 위와 같은 방식으로 움직일 때 총 몇 분 후에 모두 편의점에 도착하는지를 구하는 프로그램
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    void goBase(int t) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	if (t > m) return;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	BFS(t);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	int min_dist = INF;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	int min_x = -1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	int min_y = -1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	for (int i = 0; i < n; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		for (int j = 0; j < n; j++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    			if (base[i][j] == 1 && dist[i][j] < min_dist) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                				min_dist = dist[i][j];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                				min_x = i;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                				min_y = j;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                			}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	player[t] = { min_x, min_y };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	base[min_x][min_y] = -1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                int main() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	ios::sync_with_stdio(0); cin.tie(0); cout.tie(0);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	//freopen("sample_input.txt", "r", stdin);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	cin >> n >> m;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	for (int i = 0; i < n; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		for (int j = 0; j < n; j++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        			cin >> base[i][j];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	for (int i = 1; i <= m; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		int x, y; cin >> x >> y;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		x--; y--;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		conv[i] = { x, y };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		player[i] = { -1, -1 };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	//print();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	for (int turn = 1;; turn++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		//cout << "turn : " << turn << "\n";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		//cout << "moveAllPlayer" << "\n";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		moveAllPlayer();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		if (isOver()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                			cout << turn << "\n";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            			return 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		//print();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		//cout << "goBase" << "\n";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		goBase(turn);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		//print();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }