#define _CRT_SECURE_NO_WARNINGS
#include <iostream>
#include <queue>
using namespace std;

const int MAXN = 20;
const int MAXM = 400;
const int INF = 1e9;

int n, m, c;

int road[MAXN + 10][MAXN + 10];

int car_x, car_y, battery;
pair<int, int> start_pos[MAXM + 10];
pair<int, int> end_pos[MAXM + 10];
int arrived[MAXM + 10];

int dist[MAXN + 10][MAXN + 10];

int dx[4] = { 0,1,0,-1 };
int dy[4] = { 1,0,-1,0 };

void print() {
	cout << "car : " << car_x << " " << car_y << "\n";
    	cout << "battery : " << battery << "\n";
        	cout << "road" << "\n";
            	for (int i = 0; i < n; i++) {
                		for (int j = 0; j < n; j++) {
                        			cout << road[i][j] << " ";
                                    		}
                                            		cout << "\n";
                                                    	}
                                                        	cout << "\n";

                                                            	cout << "pos info" << "\n";
                                                                	for (int i = 1; i <= m; i++) {
                                                                    		cout << i << " : " << start_pos[i].first << " " << start_pos[i].second << " >>> " << end_pos[i].first << " " << end_pos[i].second << "\n";
                                                                            	}
                                                                                	cout << "\n";

                                                                                    	cout << "arrived" << "\n";
                                                                                        	for (int i = 1; i <= m; i++) {
                                                                                            		cout << i << " : " << arrived[i] << "\n";
                                                                                                    	}
                                                                                                        	cout << "\n";
                                                                                                            }

                                                                                                            bool isOver() {
                                                                                                            	for (int i = 1; i <= m; i++) {
                                                                                                                		if (arrived[i] == 0) return false;
                                                                                                                        	}
                                                                                                                            	return true;
                                                                                                                                }

                                                                                                                                bool inRange(int x, int y) {
                                                                                                                                	return (x >= 0 && x < n && y >= 0 && y < n);
                                                                                                                                    }

                                                                                                                                    void getDist(int x, int y) {
                                                                                                                                    	for (int i = 0; i < n; i++) {
                                                                                                                                        		for (int j = 0; j < n; j++) {
                                                                                                                                                			dist[i][j] = -1;
                                                                                                                                                            		}
                                                                                                                                                                    	}
                                                                                                                                                                        	queue<pair<int, int>> q;

                                                                                                                                                                            	q.push({ x, y });
                                                                                                                                                                                	dist[x][y] = 0;
                                                                                                                                                                                    	while (!q.empty()) {
                                                                                                                                                                                        		int cx = q.front().first;
                                                                                                                                                                                                		int cy = q.front().second;
                                                                                                                                                                                                        		q.pop();

                                                                                                                                                                                                                		for (int dir = 0; dir < 4; dir++) {
                                                                                                                                                                                                                        			int nx = cx + dx[dir];
                                                                                                                                                                                                                                    			int ny = cy + dy[dir];

                                                                                                                                                                                                                                                			if (inRange(nx, ny) && dist[nx][ny] == -1 && road[nx][ny] == 0) {
                                                                                                                                                                                                                                                            				q.push({ nx, ny });
                                                                                                                                                                                                                                                                            				dist[nx][ny] = dist[cx][cy] + 1;
                                                                                                                                                                                                                                                                                            			}
                                                                                                                                                                                                                                                                                                        		}
                                                                                                                                                                                                                                                                                                                	}
                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                    int main() {
                                                                                                                                                                                                                                                                                                                    	ios::sync_with_stdio(0); cin.tie(0); cout.tie(0);
                                                                                                                                                                                                                                                                                                                        	//freopen("sample_input.txt", "r", stdin);

                                                                                                                                                                                                                                                                                                                            	cin >> n >> m >> c;
                                                                                                                                                                                                                                                                                                                                	for (int i = 0; i < n; i++) {
                                                                                                                                                                                                                                                                                                                                    		for (int j = 0; j < n; j++) {
                                                                                                                                                                                                                                                                                                                                            			cin >> road[i][j];
                                                                                                                                                                                                                                                                                                                                                        		}
                                                                                                                                                                                                                                                                                                                                                                	}

                                                                                                                                                                                                                                                                                                                                                                    	cin >> car_x >> car_y;
                                                                                                                                                                                                                                                                                                                                                                        	car_x--; car_y--;
                                                                                                                                                                                                                                                                                                                                                                            	battery = c;

                                                                                                                                                                                                                                                                                                                                                                                	for (int i = 1; i <= m; i++) {
                                                                                                                                                                                                                                                                                                                                                                                    		int xs, ys, xe, ye; cin >> xs >> ys >> xe >> ye;
                                                                                                                                                                                                                                                                                                                                                                                            		xs--; ys--; xe--; ye--;
                                                                                                                                                                                                                                                                                                                                                                                                    		start_pos[i] = { xs, ys };
                                                                                                                                                                                                                                                                                                                                                                                                            		end_pos[i] = { xe, ye };
                                                                                                                                                                                                                                                                                                                                                                                                                    		arrived[i] = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                            	}

                                                                                                                                                                                                                                                                                                                                                                                                                                	//print();

                                                                                                                                                                                                                                                                                                                                                                                                                                    	while (1) {
                                                                                                                                                                                                                                                                                                                                                                                                                                        		getDist(car_x, car_y);
                                                                                                                                                                                                                                                                                                                                                                                                                                                		
                                                                                                                                                                                                                                                                                                                                                                                                                                                        		int min_dist = INF;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                		int min_x = INF;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		int min_y = INF;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		int target = 0;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		for (int i = 1; i <= m; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                			if (arrived[i]) continue;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            			int cx = start_pos[i].first;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        			int cy = start_pos[i].second;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    			if (min_dist > dist[cx][cy] || (min_dist == dist[cx][cy] && min_x > cx) || (min_dist == dist[cx][cy] && min_x == cx && min_y > cy)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                				min_dist = dist[cx][cy];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                				min_x = cx;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                				min_y = cy;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                				target = i;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                			}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		if (battery <= dist[min_x][min_y]) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            			battery = -1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        			break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		car_x = min_x;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		car_y = min_y;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		battery -= dist[min_x][min_y];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		//print();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		getDist(car_x, car_y);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		if (battery < dist[end_pos[target].first][end_pos[target].second]) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            			battery = -1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        			break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		car_x = end_pos[target].first;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		car_y = end_pos[target].second;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		battery += dist[end_pos[target].first][end_pos[target].second];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		arrived[target] = 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		//print();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		if (isOver()) break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	cout << battery << "\n";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	return 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }